# Capstone Module 3 Part 1

#### Objectives
0. Program Setup
1. Create dataframe with postal codes ('Postcode', 'Borough','Neighborhood')
2. Data Cleaning for Presentation

#### Step 1: Data Importing and Formatting

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
website_url = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

In [2]:
soupdata = BeautifulSoup(website_url,'lxml')

In [3]:
Table = soupdata.find('table',{'class':'wikitable sortable'})

In [4]:
headers="Postcode,Borough,Neighbourhood"

#### Step 2: Filtering values with "tr" and seperating values with "td" by comma

In [7]:
table1=""
for tr in Table.find_all('tr'):
    row1=""
    for tds in tr.find_all('td'):
        row1=row1+","+tds.text
    table1=table1+row1[1:]

#### Step 3: Convert data into .csv format and load into variable "df" for further use

In [20]:
file=open("toronto_wiki.csv","wb")
#file.write(bytes(headers,encoding="ascii",errors="ignore"))
file.write(bytes(table1,encoding="ascii",errors="ignore"))
df = pd.read_csv('toronto_wiki.csv',header=None)
df.columns=["Postalcode","Borough","Neighbourhood"]

#### Step 4: Only process the cells that have an assigned "borough". Ignoring cells with a "borough" that is Not assigned. Droping row where borough is "Not assigned"

In [21]:
indexNames = df[ df['Borough'] =='Not assigned'].index
df.drop(indexNames , inplace=True)

#### Step 5: If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough

In [22]:
df.loc[df['Neighbourhood'] =='Not assigned' , 'Neighbourhood'] = df['Borough']

#### Step 6: Rows = postalcode and combined into one row with the neighborhoods separated by a comma

In [17]:
result = df.groupby(['Postalcode','Borough'], sort=False).agg( ', '.join)

In [24]:
df_new=result.reset_index()
df_new.head(12)

,Postalcode,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Harbourfront, Regent Park"
3,M6A,North York,"Lawrence Heights, Lawrence Manor"
4,M7A,Queen's Park,Queen's Park
5,M9A,Etobicoke,Islington Avenue
6,M1B,Scarborough,"Rouge, Malvern"
7,M3B,North York,Don Mills North
8,M4B,East York,"Woodbine Gardens, Parkview Hill"
9,M5B,Downtown Toronto,"Ryerson, Garden District"
10,M6B,North York,Glencairn
11,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ..."

#### Step 7: Use the .shape method to print the number of rows of your dataframe.

In [19]:
df_new.shape

(103, 3)